export function getDomRefs() {
  return {
    appTitle: document.querySelector("title"),
    headerTitle: document.querySelector(".app-header h1"),
    headerTagline: document.querySelector(".tagline"),
    languageLabel: document.getElementById("languageLabel"),
    themeLabel: document.getElementById("themeLabel"),
    languageSelect: document.getElementById("languageSelect"),
    themeSelect: document.getElementById("themeSelect"),
    rulesTitle: document.getElementById("rules-title"),
    rule1: document.getElementById("rule1"),
    rule2: document.getElementById("rule2"),
    rule3: document.getElementById("rule3"),
    rule4: document.getElementById("rule4"),
    rule5: document.getElementById("rule5"),
    rule6: document.getElementById("rule6"),
    rule7: document.getElementById("rule7"),
    rule8: document.getElementById("rule8"),
    playerNameInput: document.getElementById("playerName"),
    playerTwoNameInput: document.getElementById("playerTwoName"),
    twoPlayerModeInput: document.getElementById("twoPlayerMode"),
    timePerQuestionInput: document.getElementById("timePerQuestion"),
    difficultyLevelInput: document.getElementById("difficultyLevel"),
    questionThemeInput: document.getElementById("questionTheme"),
    questionCountModeInput: document.getElementById("questionCountMode"),
    customQuestionCountInput: document.getElementById("customQuestionCount"),
    playerOneLabel: document.querySelector('label[for="playerName"]'),
    playerTwoLabel: document.querySelector('label[for="playerTwoName"]'),
    secondsPerQuestionLabel: document.querySelector(
      'label[for="timePerQuestion"]',
    ),
    difficultyLevelSetupLabel: document.querySelector(
      'label[for="difficultyLevel"]',
    ),
    questionThemeLabel: document.querySelector('label[for="questionTheme"]'),
    questionCountModeLabel: document.getElementById("questionCountModeLabel"),
    customQuestionCountLabel: document.getElementById(
      "customQuestionCountLabel",
    ),
    twoPlayerModeLabel: document.querySelector('label[for="twoPlayerMode"]'),
    difficultyInfo: document.getElementById("difficultyInfo"),
    livePrefix: document.getElementById("livePrefix"),
    liveName: document.getElementById("liveName"),
    statePrefix: document.getElementById("statePrefix"),
    turnPrefix: document.getElementById("turnPrefix"),
    timePrefix: document.getElementById("timePrefix"),
    difficultyPrefix: document.getElementById("difficultyPrefix"),
    scorePrefix: document.getElementById("scorePrefix"),
    scoreboardPrefix: document.getElementById("scoreboardPrefix"),
    questionPrefix: document.getElementById("questionPrefix"),
    scoreLabel: document.getElementById("scoreLabel"),
    scoreboardLabel: document.getElementById("scoreboardLabel"),
    progressLabel: document.getElementById("progressLabel"),
    gameStateLabel: document.getElementById("gameStateLabel"),
    difficultyLabel: document.getElementById("difficultyLabel"),
    currentPlayerLabel: document.getElementById("currentPlayerLabel"),
    timerLabel: document.getElementById("timerLabel"),
    questionText: document.getElementById("questionText"),
    answersContainer: document.getElementById("answers"),
    startBtn: document.getElementById("startBtn"),
    nextBtn: document.getElementById("nextBtn"),
    replayBtn: document.getElementById("replayBtn"),
    resultTitle: document.querySelector("#resultBox h2"),
    resultText: document.getElementById("resultText"),
  };
}
